ignore:
  - flowmazonbackend/flowmazonapi/Migrations

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
      api:
        target: 90%
        threshold: 1%
        paths:
          - flowmazonbackend
      
# changes